name: 8820-book-env-2
channels:
- conda-forge
dependencies:
- python
- nb_conda_kernels
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- emcee
- ptemcee
- zeus-mcmc
- corner
- mkl-service
- jupyter_nbextensions_configurator
- scikit-learn
- scikit-image
- pydoe
- jupyter-book
- sphinx
- ghp-import
- pip
- pip:
  - gpy
  - gpyopt  
  - pymultinest
  - pymc3
  - arviz
